baseURL = "/"
relativeURLs = true
languageCode = "zh-cn"
title = "Fight For Freedom of Speech"
auth = "Fight For Freedom of Speech"
description = "盘点中国近年文字狱事件，为中国网警执法案例做义务宣传！#言论自由 Collection of incidents that Chinese authorities violate rights of speech freedom. #speechfreedom"
theme = "jeffprod"
copyright = "Copyright © Fight For Freedom of Speech"
enableRobotsTXT = true
disableAliases = true
googleAnalytics = "UA-151212685-1"
summaryLength = 50
media_folder = "/site/static/images/uploads"
public_folder = "/static/images/uploads"

[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

[permalinks]
    post = "/post/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"

[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true